# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle from saeed-g7

on:
  push:
#     branches: [ Ivan ]
    branches: saeed_branch-tartan-smarthome-group-7
  pull_request:
    branches: saeed_branch-tartan-smarthome-group-7

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
#     run this if gradlew is not working; we need to create a wrapper for gradle
    - name: Create wrapper
      run: gradle wrapper
    - name: Grant execute permission for gradlew
      working-directory: ./smart-home/Platform/
      run: chmod +x gradlew 
    - name: Build with Gradle
      working-directory: ./smart-home/Platform/
      run: ./gradlew build
    - name: Testing with gradle
      working-directory: ./smart-home/Platform/
      run: ./gradlew test

